#!/bin/sh
set -e
package_name=brave-tweaks

case "$1" in
  remove)
#    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/chromium.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/brave-browser-stable"
    ;;
  purge)
#    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/chromium.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/brave-browser-stable"
;;
esac
exit 0
