#!/bin/sh
set -e
package_name=chromium-tweaks
ln -sf /usr/bin/chromium /usr/bin/chromium-browser

case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/chromium.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/chromium"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/chromium.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/chromium"
;;
esac
exit 0
