#!/bin/sh
set -e
package_name=chromium-tweaks
mkdir -p "/usr/share/dpkgdivert/chromium-tweaks"

ln -sf /usr/bin/chromium /usr/bin/chromium-browser

case "$1" in
  install)
    dpkg-divert --package "$package_name" --divert "/usr/bin/chromium.orig" --rename "/usr/bin/chromium"
    dpkg-divert --package "$package_name" --divert "/usr/share/applications/chromium-browser.desktop" --rename "/usr/share/applications/chromium.desktop"
    ;;
  upgrade)
if [ "$(dpkg-divert --list "/usr/share/applications/chromium.desktop")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/applications/chromium-browser.desktop" --rename "/usr/share/applications/chromium.desktop"
fi
if [ "$(dpkg-divert --list "/usr/bin/chromium")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/bin/chromium.orig" --rename "/usr/bin/chromium"
fi
;;
esac
exit 0
